// База данных товаров

const PRODUCTS = [
  {
    id: "silk-dress",
    name: "Silk Slip Dress",
    price: 189,
    category: "dresses",
    colors: ["ivory"],
    sizes: ["XS", "S", "M"],
    date: "2026-03-17",
  },
  {
    id: "silk-dress-2",
    name: "Silk Slip Dress (Black)",
    price: 189,
    category: "dresses",
    colors: ["black"],
    sizes: ["XS", "S", "M"],
    date: "2026-03-17",
  },
  {
    id: "silk-dress-3",
    name: "Silk Slip Dress (Violet)",
    price: 189,
    category: "dresses",
    colors: ["violet"],
    sizes: ["XS", "S", "M"],
    date: "2026-03-17",
  },
  {
    id: "silk-dress-4",
    name: "Silk Slip Dress (Pink)",
    price: 189,
    category: "dresses",
    colors: ["pink"],
    sizes: ["XS", "S", "M"],
    date: "2026-03-17",
  },
  {
    id: "silk-dress-5",
    name: "Silk Slip Dress (Blue)",
    price: 189,
    category: "dresses",
    colors: ["blue"],
    sizes: ["XS", "S", "M"],
    date: "2026-03-17",
  },
  {
    id: "silk-dress-6",
    name: "Silk Slip Dress (Yellow)",
    price: 189,
    category: "dresses",
    colors: ["yellow"],
    sizes: ["XS", "S", "M"],
    date: "2026-03-17",
  },
  {
    id: "silk-dress-7",
    name: "Silk Slip Dress (Teal)",
    price: 189,
    category: "dresses",
    colors: ["teal"],
    sizes: ["XS", "S", "M"],
    date: "2026-03-17",
  },
  {
    id: "linen-trench",
    name: "Linen Trench",
    price: 320,
    category: "outerwear",
    colors: ["ivory"],
    sizes: ["XS", "S", "M", "L"],
    date: "2026-03-20",
  },
  {
    id: "linen-trench-2",
    name: "Linen Trench (Black)",
    price: 320,
    category: "outerwear",
    colors: ["black"],
    sizes: ["XS", "S", "M", "L"],
    date: "2026-03-20",
  },
  {
    id: "cashmere-knit",
    name: "Cashmere Knit",
    price: 245,
    category: "knitwear",
    colors: ["ivory"],
    sizes: ["XS", "S", "M", "L", "XL"],
    date: "2026-03-15",
  },
  {
    id: "cashmere-knit-2",
    name: "Cashmere Knit (Black)",
    price: 245,
    category: "knitwear",
    colors: ["black"],
    sizes: ["XS", "S", "M", "L", "XL"],
    date: "2026-03-15",
  },
  {
    id: "cashmere-knit-3",
    name: "Cashmere Knit (Violet)",
    price: 245,
    category: "knitwear",
    colors: ["violet"],
    sizes: ["XS", "S", "M", "L", "XL"],
    date: "2026-03-15",
  },
  {
    id: "cashmere-knit-4",
    name: "Cashmere Knit (Pink)",
    price: 245,
    category: "knitwear",
    colors: ["pink"],
    sizes: ["XS", "S", "M", "L", "XL"],
    date: "2026-03-15",
  },
  {
    id: "cashmere-knit-5",
    name: "Cashmere Knit (Blue)",
    price: 245,
    category: "knitwear",
    colors: ["blue"],
    sizes: ["XS", "S", "M", "L", "XL"],
    date: "2026-03-15",
  },
  {
    id: "cashmere-knit-6",
    name: "Cashmere Knit (Yellow)",
    price: 245,
    category: "knitwear",
    colors: ["yellow"],
    sizes: ["XS", "S", "M", "L", "XL"],
    date: "2026-03-15",
  },
  {
    id: "cashmere-cardigan",
    name: "Cashmere Cardigan",
    price: 200,
    category: "knitwear",
    colors: ["ivory"],
    sizes: ["XS", "S", "M", "L", "XL"],
    date: "2026-03-18",
  },
  {
    id: "cashmere-cardigan-2",
    name: "Cashmere Cardigan (Black)",
    price: 200,
    category: "knitwear",
    colors: ["black"],
    sizes: ["XS", "S", "M", "L", "XL"],
    date: "2026-03-18",
  },
  {
    id: "cashmere-cardigan-3",
    name: "Cashmere Cardigan (Violet)",
    price: 200,
    category: "knitwear",
    colors: ["violet"],
    sizes: ["XS", "S", "M", "L", "XL"],
    date: "2026-03-18",
  },
  {
    id: "cashmere-cardigan-4",
    name: "Cashmere Cardigan (Pink)",
    price: 200,
    category: "knitwear",
    colors: ["pink"],
    sizes: ["XS", "S", "M", "L", "XL"],
    date: "2026-03-18",
  },
  {
    id: "knit-turtleneck",
    name: "Knit Turtleneck",
    price: 220,
    category: "knitwear",
    colors: ["ivory"],
    sizes: ["XS", "S", "L", "XL"],
    date: "2026-03-18",
  },
  {
    id: "knit-turtleneck-2",
    name: "Knit Turtleneck (Black)",
    price: 220,
    category: "knitwear",
    colors: ["black"],
    sizes: ["XS", "S", "L", "XL"],
    date: "2026-03-18",
  },
  {
    id: "knit-turtleneck-3",
    name: "Knit Turtleneck (Violet)",
    price: 220,
    category: "knitwear",
    colors: ["violet"],
    sizes: ["XS", "S", "L", "XL"],
    date: "2026-03-18",
  },
  {
    id: "knit-turtleneck-4",
    name: "Knit Turtleneck (Pink)",
    price: 220,
    category: "knitwear",
    colors: ["pink"],
    sizes: ["XS", "S", "L", "XL"],
    date: "2026-03-18",
  },
  {
    id: "knit-turtleneck-5",
    name: "Knit Turtleneck (Blue)",
    price: 220,
    category: "knitwear",
    colors: ["blue"],
    sizes: ["XS", "S", "L", "XL"],
    date: "2026-03-18",
  },
  {
    id: "wide-leg-trousers",
    name: "Wide Leg Trousers",
    price: 290,
    category: "trousers",
    colors: ["ivory"],
    sizes: ["S", "M", "L", "XL"],
    date: "2026-03-10",
  },
  {
    id: "wide-leg-trousers-2",
    name: "Wide Leg Trousers (Black)",
    price: 290,
    category: "trousers",
    colors: ["black"],
    sizes: ["S", "M", "L", "XL"],
    date: "2026-03-10",
  },
  {
    id: "wide-leg-trousers-3",
    name: "Wide Leg Trousers (Violet)",
    price: 290,
    category: "trousers",
    colors: ["violet"],
    sizes: ["S", "M", "L", "XL"],
    date: "2026-03-10",
  },
  {
    id: "silk-top",
    name: "Silk Camisole Top",
    price: 175,
    category: "tops",
    colors: ["ivory"],
    sizes: ["XS", "S", "M"],
    date: "2026-03-13",
  },
  {
    id: "silk-top-2",
    name: "Silk Camisole Top (Black)",
    price: 175,
    category: "tops",
    colors: ["black"],
    sizes: ["XS", "S", "M"],
    date: "2026-03-13",
  },
  {
    id: "silk-top-3",
    name: "Silk Camisole Top (Violet)",
    price: 175,
    category: "tops",
    colors: ["violet"],
    sizes: ["XS", "S", "M"],
    date: "2026-03-13",
  },
  {
    id: "silk-top-4",
    name: "Silk Camisole Top (Pink)",
    price: 175,
    category: "tops",
    colors: ["pink"],
    sizes: ["XS", "S", "M"],
    date: "2026-03-13",
  },
  {
    id: "silk-top-5",
    name: "Silk Camisole Top (Blue)",
    price: 175,
    category: "tops",
    colors: ["blue"],
    sizes: ["XS", "S", "M"],
    date: "2026-03-13",
  },
  {
    id: "silk-top-6",
    name: "Silk Camisole Top (Yellow)",
    price: 175,
    category: "tops",
    colors: ["yellow"],
    sizes: ["XS", "S", "M"],
    date: "2026-03-13",
  },
  {
    id: "silk-top-7",
    name: "Silk Camisole Top (Teal)",
    price: 175,
    category: "tops",
    colors: ["teal"],
    sizes: ["XS", "S", "M"],
    date: "2026-03-13",
  },
  {
    id: "linen-shirt",
    name: "Linen Oversized Shirt",
    price: 190,
    category: "shirts",
    colors: ["ivory"],
    sizes: ["S", "M", "L", "XL"],
    date: "2026-03-11",
  },
  {
    id: "linen-shirt-2",
    name: "Linen Oversized Shirt (Black)",
    price: 190,
    category: "shirts",
    colors: ["black"],
    sizes: ["S", "M", "L", "XL"],
    date: "2026-03-11",
  },
  {
    id: "linen-shirt-5",
    name: "Linen Oversized Shirt (Blue)",
    price: 190,
    category: "shirts",
    colors: ["blue"],
    sizes: ["S", "M", "L", "XL"],
    date: "2026-03-11",
  },
  {
    id: "linen-shirt-7",
    name: "Linen Oversized Shirt (Teal)",
    price: 190,
    category: "shirts",
    colors: ["teal"],
    sizes: ["S", "M", "L", "XL"],
    date: "2026-03-11",
  },
  {
    id: "satin-blazer",
    name: "Satin Blazer",
    price: 290,
    category: "outerwear",
    colors: ["ivory"],
    sizes: ["XS", "S", "M", "L", "XL"],
    date: "2026-03-18",
  },
  {
    id: "satin-blazer-2",
    name: "Satin Blazer (Black)",
    price: 290,
    category: "outerwear",
    colors: ["black"],
    sizes: ["XS", "S", "M", "L", "XL"],
    date: "2026-03-18",
  },
  {
    id: "satin-blazer-3",
    name: "Satin Blazer (Violet)",
    price: 290,
    category: "outerwear",
    colors: ["violet"],
    sizes: ["XS", "S", "M", "L", "XL"],
    date: "2026-03-18",
  },
  {
    id: "satin-blazer-4",
    name: "Satin Blazer (Pink)",
    price: 290,
    category: "outerwear",
    colors: ["pink"],
    sizes: ["XS", "S", "M", "L", "XL"],
    date: "2026-03-18",
  },
  {
    id: "satin-blazer-5",
    name: "Satin Blazer (Blue)",
    price: 290,
    category: "outerwear",
    colors: ["blue"],
    sizes: ["XS", "S", "M", "L", "XL"],
    date: "2026-03-18",
  },
  {
    id: "satin-blazer-6",
    name: "Satin Blazer (Yellow)",
    price: 290,
    category: "outerwear",
    colors: ["yellow"],
    sizes: ["XS", "S", "M", "L", "XL"],
    date: "2026-03-18",
  },
  {
    id: "satin-blazer-7",
    name: "Satin Blazer (Teal)",
    price: 290,
    category: "outerwear",
    colors: ["teal"],
    sizes: ["XS", "S", "M", "L", "XL"],
    date: "2026-03-18",
  },
  {
    id: "silk-blouse",
    name: "Silk Blouse",
    price: 165,
    category: "blouses",
    colors: ["ivory"],
    sizes: ["XS", "S", "M", "L"],
    date: "2026-03-14",
  },
  {
    id: "silk-blouse-2",
    name: "Silk Blouse (Black)",
    price: 165,
    category: "blouses",
    colors: ["black"],
    sizes: ["XS", "S", "M", "L"],
    date: "2026-03-14",
  },
  {
    id: "silk-blouse-3",
    name: "Silk Blouse (Violet)",
    price: 165,
    category: "blouses",
    colors: ["violet"],
    sizes: ["XS", "S", "M", "L"],
    date: "2026-03-14",
  },
  {
    id: "silk-blouse-4",
    name: "Silk Blouse (Pink)",
    price: 165,
    category: "blouses",
    colors: ["pink"],
    sizes: ["XS", "S", "M", "L"],
    date: "2026-03-14",
  },
  {
    id: "silk-blouse-5",
    name: "Silk Blouse (Blue)",
    price: 165,
    category: "blouses",
    colors: ["blue"],
    sizes: ["XS", "S", "M", "L"],
    date: "2026-03-14",
  },
  {
    id: "silk-blouse-7",
    name: "Silk Blouse (Teal)",
    price: 165,
    category: "blouses",
    colors: ["teal"],
    sizes: ["XS", "S", "M", "L"],
    date: "2026-03-14",
  },
  {
    id: "slip-skirt",
    name: "Slip Skirt",
    price: 290,
    category: "skirts",
    colors: ["ivory"],
    sizes: ["XS", "S", "M", "L"],
    date: "2026-03-12",
  },
  {
    id: "slip-skirt-2",
    name: "Slip Skirt (Black)",
    price: 290,
    category: "skirts",
    colors: ["black"],
    sizes: ["XS", "S", "M", "L"],
    date: "2026-03-12",
  },
  {
    id: "slip-skirt-3",
    name: "Slip Skirt (Violet)",
    price: 290,
    category: "skirts",
    colors: ["violet"],
    sizes: ["XS", "S", "M", "L"],
    date: "2026-03-12",
  },
  {
    id: "slip-skirt-4",
    name: "Slip Skirt (Pink)",
    price: 290,
    category: "skirts",
    colors: ["pink"],
    sizes: ["XS", "S", "M", "L"],
    date: "2026-03-12",
  },
  {
    id: "slip-skirt-5",
    name: "Slip Skirt (Blue)",
    price: 290,
    category: "skirts",
    colors: ["blue"],
    sizes: ["XS", "S", "M", "L"],
    date: "2026-03-12",
  },
  {
    id: "slip-skirt-6",
    name: "Slip Skirt (Yellow)",
    price: 290,
    category: "skirts",
    colors: ["yellow"],
    sizes: ["XS", "S", "M", "L"],
    date: "2026-03-12",
  },
  {
    id: "slip-skirt-7",
    name: "Slip Skirt (Teal)",
    price: 290,
    category: "skirts",
    colors: ["teal"],
    sizes: ["XS", "S", "M", "L"],
    date: "2026-03-12",
  },

  // --- ACCESSORIES ---

  {
    id: "silk-scarf",
    name: "Silk Square Scarf",
    price: 65,
    category: "accessories",
    colors: ["ivory"],
    sizes: ["ONE SIZE"],
    date: "2026-03-22",
  },
  {
    id: "silk-scarf-3",
    name: "Silk Square Scarf (Violet)",
    price: 65,
    category: "accessories",
    colors: ["violet"],
    sizes: ["ONE SIZE"],
    date: "2026-03-22",
  },
  {
    id: "silk-scarf-4",
    name: "Silk Square Scarf (Pink)",
    price: 65,
    category: "accessories",
    colors: ["pink"],
    sizes: ["ONE SIZE"],
    date: "2026-03-22",
  },
  {
    id: "silk-scarf-7",
    name: "Silk Square Scarf (Teal)",
    price: 65,
    category: "accessories",
    colors: ["teal"],
    sizes: ["ONE SIZE"],
    date: "2026-03-22",
  },

  {
    id: "leather-belt",
    name: "Classic Leather Belt (Ivory)",
    price: 85,
    category: "accessories",
    colors: ["ivory"],
    sizes: ["S", "M", "L"],
    date: "2026-03-21",
  },
  {
    id: "leather-belt-2",
    name: "Classic Leather Belt (Black)",
    price: 85,
    category: "accessories",
    colors: ["black"],
    sizes: ["S", "M", "L"],
    date: "2026-03-21",
  },

  {
    id: "cashmere-beanie",
    name: "Ribbed Cashmere Beanie",
    price: 95,
    category: "accessories",
    colors: ["ivory"],
    sizes: ["ONE SIZE"],
    date: "2026-03-16",
  },
  {
    id: "cashmere-beanie-2",
    name: "Ribbed Cashmere Beanie (Black)",
    price: 95,
    category: "accessories",
    colors: ["black"],
    sizes: ["ONE SIZE"],
    date: "2026-03-16",
  },
  {
    id: "cashmere-beanie-5",
    name: "Ribbed Cashmere Beanie (Blue)",
    price: 95,
    category: "accessories",
    colors: ["blue"],
    sizes: ["ONE SIZE"],
    date: "2026-03-16",
  },
  {
    id: "cashmere-beanie-6",
    name: "Ribbed Cashmere Beanie (Yellow)",
    price: 95,
    category: "accessories",
    colors: ["yellow"],
    sizes: ["ONE SIZE"],
    date: "2026-03-16",
  },

  {
    id: "silver-hoops",
    name: "Minimalist Silver Hoops",
    price: 110,
    category: "accessories",
    colors: ["ivory"],
    sizes: ["ONE SIZE"],
    date: "2026-03-25",
  },
  {
    id: "gold-necklace-6",
    name: "Delicate Gold Chain Necklace",
    price: 135,
    category: "accessories",
    colors: ["yellow"],
    sizes: ["ONE SIZE"],
    date: "2026-03-25",
  },
  {
    id: "canvas-tote",
    name: "Lune Canvas Tote",
    price: 45,
    category: "accessories",
    colors: ["ivory"],
    sizes: ["ONE SIZE"],
    date: "2026-03-10",
  },
  {
    id: "leather-tote-2",
    name: "Soft Leather Tote",
    price: 210,
    category: "accessories",
    colors: ["black"],
    sizes: ["ONE SIZE"],
    date: "2026-03-24",
  },
];
